# Minimal project config. Both functions are called without a Supabase JWT:
# the licence API is public by design, the admin API is protected by ADMIN_TOKEN.
project_id = "copypaste-unlocker"

[functions.license]
verify_jwt = false

[functions.admin]
verify_jwt = false
